steps:
  # Decrypt the SSH key.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "kms",
        "decrypt",
        "--ciphertext-file=deploy_key.enc",
        "--plaintext-file=/root/.ssh/id_rsa",
        "--location=global",
        "--keyring=${_KEY_RING}",
        "--key=${_KEY_NAME}",
      ]

  # Decrypt the npm credentials.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "kms",
        "decrypt",
        "--ciphertext-file=npmrc.enc",
        "--plaintext-file=npmrc",
        "--location=global",
        "--keyring=${_KEY_RING}",
        "--key=${_KEY_NAME}",
      ]

  # Set up git with key and domain.
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        ssh-keyscan github.com >> /root/.ssh/known_hosts

  # Clone the repository.
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "git@github.com:${_REPOSITORY_ORG}/${_REPOSITORY_NAME}"]

  # Fetch all tags so stateless history calculations resolve correctly.
  - name: "gcr.io/cloud-builders/git"
    dir: "${_REPOSITORY_NAME}"
    args: ["fetch", "--tags"]

  # Set up the Git configuration.
  - name: "gcr.io/cloud-builders/git"
    dir: "${_REPOSITORY_NAME}"
    args: ["config", "--global", "user.email", "firebase-oss-bot@google.com"]
  - name: "gcr.io/cloud-builders/git"
    dir: "${_REPOSITORY_NAME}"
    args: ["config", "--global", "user.name", "Google Open Source Bot"]

  # Set up the npm credentials.
  - name: "gcr.io/$PROJECT_ID/package-builder"
    entrypoint: "bash"
    args: ["-c", "cp -v npmrc ~/.npmrc"]

  # Publish the package.
  - name: "gcr.io/$PROJECT_ID/package-builder"
    dir: "${_REPOSITORY_NAME}"
    entrypoint: bash
    args:
      - "-c"
      - |
        # Map our Cloud Build environment variables for the shell script execution
        export GITHUB_TOKEN=$$GITHUB_TOKEN

        ./scripts/publish.sh ${_BUMP_TYPE} \
          $([ "${_PRERELEASE}" = "true" ] && echo "--prerelease") \
          $([ "${_DRY_RUN}" = "false" ] && echo "--no-dry-run") \
          $([ "${_FORCE}" = "true" ] && echo "--force") \
          --org=${_REPOSITORY_ORG} \
          --repository=${_REPOSITORY_NAME} \
          ${_DIST_TAG}

    secretEnv: ["GITHUB_TOKEN"]

options:
  volumes:
    - name: "ssh"
      path: /root/.ssh

substitutions:
  _BUMP_TYPE: "patch"
  _PRERELEASE: "false"
  _DRY_RUN: "true"
  _FORCE: "false"
  _DIST_TAG: "latest"
  _KEY_RING: "npm-publish-keyring"
  _KEY_NAME: "publish"
  _REPOSITORY_ORG: "firebase"
  _REPOSITORY_NAME: "firebase-functions"
  _BRANCH: ""

availableSecrets:
  secretManager:
    - versionName: projects/firebase-functions-publishing/secrets/firebase-functions-github-pat/versions/latest
      env: "GITHUB_TOKEN"
