steps:
  # 1. Set up SSH key and Git config.
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        mkdir -p /root/.ssh
        echo "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        ssh-keyscan github.com >> /root/.ssh/known_hosts
    secretEnv: ["SSH_KEY"]

  # 2. Clone the repository.
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "git@github.com:${_REPOSITORY_ORG}/${_REPOSITORY_NAME}"]

  # 3. Fetch all tags so stateless history calculations resolve correctly.
  - name: "gcr.io/cloud-builders/git"
    dir: "${_REPOSITORY_NAME}"
    args: ["fetch", "--tags"]

  # 4. Set up the Git configuration.
  - name: "gcr.io/cloud-builders/git"
    dir: "${_REPOSITORY_NAME}"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git config --global user.email "firebase-oss-bot@google.com"
        git config --global user.name "Google Open Source Bot"

  # 5. Publish the package.
  - name: "gcr.io/$PROJECT_ID/package-builder"
    dir: "${_REPOSITORY_NAME}"
    entrypoint: bash
    env:
      - "BUILD_ID=${BUILD_ID}"
    args:
      - "-c"
      - |
        echo "$$NPMRC_CONTENT" > ~/.npmrc

        export GITHUB_TOKEN=$$GITHUB_TOKEN

        ./scripts/publish.sh ${_BUMP_TYPE} \
          $([ "${_PRERELEASE}" = "true" ] && echo "--prerelease") \
          $([ "${_DRY_RUN}" = "false" ] && echo "--no-dry-run") \
          $([ "${_FORCE}" = "true" ] && echo "--force") \
          $([ -n "${_BRANCH}" ] && echo "--branch ${_BRANCH}") \
          --org=${_REPOSITORY_ORG} \
          --repository=${_REPOSITORY_NAME} \
          $([ -n "${_DIST_TAG}" ] && echo "--dist-tag ${_DIST_TAG}")
    secretEnv: ["GITHUB_TOKEN", "NPMRC_CONTENT"]

options:
  volumes:
    - name: "ssh"
      path: /root/.ssh

substitutions:
  _BUMP_TYPE: "patch"
  _PRERELEASE: "false"
  _DRY_RUN: "true"
  _FORCE: "false"
  _DIST_TAG: ""
  _REPOSITORY_ORG: "firebase"
  _REPOSITORY_NAME: "firebase-functions"
  _BRANCH: ""

availableSecrets:
  secretManager:
    - versionName: projects/firebase-functions-publishing/secrets/firebase-functions-github-pat/versions/latest
      env: "GITHUB_TOKEN"
    - versionName: projects/firebase-functions-publishing/secrets/firebase-functions-deploy-key/versions/latest
      env: "SSH_KEY"
    - versionName: projects/firebase-functions-publishing/secrets/firebase-functions-npm-token/versions/latest
      env: "NPMRC_CONTENT"
