suite:
  name: v1_auth
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Auth trigger tests"
  version: v1
  service: auth

  functions:
    - name: authUserOnCreateTests
      trigger: onCreate
      timeout: 540
      collection: authUserOnCreateTests

    - name: authUserOnDeleteTests
      trigger: onDelete
      timeout: 540
      collection: authUserOnDeleteTests

    - name: authUserBeforeCreateTests
      trigger: beforeCreate
      timeout: 540
      collection: authBeforeCreateTests

    - name: authUserBeforeSignInTests
      trigger: beforeSignIn
      timeout: 540
      collection: authBeforeSignInTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"