suite:
  name: v1_auth_before_signin
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Auth beforeSignIn trigger test"
  version: v1
  service: auth

  functions:
    - name: authUserBeforeSignInTests
      trigger: beforeSignIn
      timeout: 540
      collection: authBeforeSignInTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"