suite:
  name: v1_auth_before_create
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Auth beforeCreate trigger test"
  version: v1
  service: auth

  functions:
    - name: authUserBeforeCreateTests
      trigger: beforeCreate
      timeout: 540
      collection: authBeforeCreateTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"