suite:
  name: v1_database
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Realtime Database trigger tests"
  version: v1
  service: database

  functions:
    - name: databaseRefOnCreateTests
      trigger: onCreate
      path: "dbTests/{testId}/start"
      timeout: 540
      collection: databaseRefOnCreateTests

    - name: databaseRefOnDeleteTests
      trigger: onDelete
      path: "dbTests/{testId}/start"
      timeout: 540
      collection: databaseRefOnDeleteTests

    - name: databaseRefOnUpdateTests
      trigger: onUpdate
      path: "dbTests/{testId}/start"
      timeout: 540
      collection: databaseRefOnUpdateTests

    - name: databaseRefOnWriteTests
      trigger: onWrite
      path: "dbTests/{testId}/start"
      timeout: 540
      collection: databaseRefOnWriteTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"