suite:
  name: v1_pubsub
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Pub/Sub trigger tests"
  version: v1
  service: pubsub

  functions:
    - name: pubsubOnPublishTests
      trigger: onPublish
      topic: "pubsubTests"
      timeout: 540
      collection: pubsubOnPublishTests

    - name: pubsubScheduleTests
      trigger: onRun
      schedule: "every 10 hours"
      timeout: 540
      collection: pubsubScheduleTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"