suite:
  name: v1_remoteconfig
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Remote Config trigger tests"
  version: v1
  service: remoteconfig

  functions:
    - name: remoteConfigOnUpdateTests
      trigger: onUpdate
      timeout: 540
      collection: remoteConfigOnUpdateTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"