suite:
  name: v1_storage
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Storage trigger tests"
  version: v1
  service: storage

  functions:
    - name: storageOnFinalizeTests
      trigger: onFinalize
      timeout: 540
      collection: storageOnFinalizeTests

    # Note: onDelete is commented out due to bug b/372315689
    # - name: storageOnDeleteTests
    #   trigger: onDelete
    #   timeout: 540
    #   collection: storageOnDeleteTests

    - name: storageOnMetadataUpdateTests
      trigger: onMetadataUpdate
      timeout: 540
      collection: storageOnMetadataUpdateTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"