suite:
  name: v1_tasks
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 Cloud Tasks trigger tests"
  version: v1
  service: tasks

  functions:
    - name: tasksOnDispatchTests
      trigger: onDispatch
      timeout: 540
      collection: tasksOnDispatchTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"