suite:
  name: v1_testlab
  projectId: functions-integration-tests
  region: us-central1
  description: "V1 TestLab trigger tests"
  version: v1
  service: testlab

  functions:
    - name: testLabOnCompleteTests
      trigger: onComplete
      timeout: 540
      collection: testLabOnCompleteTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"