suite:
  name: v2_alerts
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 Alerts trigger tests (deployment only)"
  version: v2
  service: alerts

  functions:
    # Generic alert
    - name: alertsOnAlertPublishedTests
      trigger: onAlertPublished
      alertType: "crashlytics.newFatalIssue"
      timeout: 540

    # App Distribution alerts
    - name: alertsOnInAppFeedbackPublishedTests
      trigger: onInAppFeedbackPublished
      timeout: 540

    - name: alertsOnNewTesterIosDevicePublishedTests
      trigger: onNewTesterIosDevicePublished
      timeout: 540

    # Billing alerts
    - name: alertsOnPlanAutomatedUpdatePublishedTests
      trigger: onPlanAutomatedUpdatePublished
      timeout: 540

    - name: alertsOnPlanUpdatePublishedTests
      trigger: onPlanUpdatePublished
      timeout: 540

    # Crashlytics alerts
    - name: alertsOnNewAnrIssuePublishedTests
      trigger: onNewAnrIssuePublished
      timeout: 540

    - name: alertsOnNewFatalIssuePublishedTests
      trigger: onNewFatalIssuePublished
      timeout: 540

    - name: alertsOnNewNonFatalIssuePublishedTests
      trigger: onNewNonfatalIssuePublished
      timeout: 540

    - name: alertsOnRegressionAlertPublishedTests
      trigger: onRegressionAlertPublished
      timeout: 540

    - name: alertsOnStabilityDigestPublishedTests
      trigger: onStabilityDigestPublished
      timeout: 540

    - name: alertsOnVelocityAlertPublishedTests
      trigger: onVelocityAlertPublished
      timeout: 540

    # Performance alerts
    - name: alertsOnThresholdAlertPublishedTests
      trigger: onThresholdAlertPublished
      timeout: 540

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"