suite:
  name: v2_database
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 Realtime Database trigger tests"
  version: v2
  service: database

  functions:
    - name: databaseCreatedTests
      trigger: onValueCreated
      path: "databaseCreatedTests/{testId}/start"
      timeout: 540
      collection: databaseCreatedTests

    - name: databaseDeletedTests
      trigger: onValueDeleted
      path: "databaseDeletedTests/{testId}/start"
      timeout: 540
      collection: databaseDeletedTests

    - name: databaseUpdatedTests
      trigger: onValueUpdated
      path: "databaseUpdatedTests/{testId}/start"
      timeout: 540
      collection: databaseUpdatedTests

    - name: databaseWrittenTests
      trigger: onValueWritten
      path: "databaseWrittenTests/{testId}/start"
      timeout: 540
      collection: databaseWrittenTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"