suite:
  name: v2_eventarc
  projectId: functions-integration-tests-v2
  region: us-central1
  description: "V2 Eventarc trigger tests"
  version: v2
  service: eventarc

  functions:
    - name: eventarcOnCustomEventPublishedTests
      eventType: achieved-leaderboard
      collection: eventarcOnCustomEventPublishedTests
      timeout: 540

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"
