suite:
  name: v2_identity
  projectId: functions-integration-tests-v2
  region: us-central1
  description: "V2 Identity trigger tests"
  version: v2
  service: identity

  functions:
    - name: identityBeforeUserCreatedTests
      type: beforeUserCreated
      collection: identityBeforeUserCreatedTests
      timeout: 540

    - name: identityBeforeUserSignedInTests
      type: beforeUserSignedIn
      collection: identityBeforeUserSignedInTests
      timeout: 540

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"
