suite:
  name: v2_pubsub
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 Pub/Sub trigger tests"
  version: v2
  service: pubsub

  functions:
    - name: pubsubOnMessagePublishedTests
      trigger: onMessagePublished
      topic: "custom_message_tests"
      timeout: 540
      collection: pubsubOnMessagePublishedTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"