suite:
  name: v2_remoteconfig
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 Remote Config trigger tests"
  version: v2
  service: remoteconfig

  functions:
    - name: remoteConfigOnConfigUpdatedTests
      trigger: onConfigUpdated
      timeout: 540
      collection: remoteConfigOnConfigUpdatedTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"