suite:
  name: v2_scheduler
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 Scheduler trigger tests"
  version: v2
  service: scheduler

  functions:
    - name: schedule
      trigger: onSchedule
      schedule: "every 10 hours"
      timeout: 540
      collection: schedulerOnScheduleV2Tests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"