suite:
  name: v2_storage
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 Storage trigger tests"
  version: v2
  service: storage

  functions:
    - name: storageOnObjectFinalizedTests
      trigger: onObjectFinalized
      timeout: 540
      collection: storageOnObjectFinalizedTests

    - name: storageOnObjectDeletedTests
      trigger: onObjectDeleted
      timeout: 540
      collection: storageOnObjectDeletedTests

    - name: storageOnObjectMetadataUpdatedTests
      trigger: onObjectMetadataUpdated
      timeout: 540
      collection: storageOnObjectMetadataUpdatedTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"