suite:
  name: v2_tasks
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 Cloud Tasks trigger tests"
  version: v2
  service: tasks

  functions:
    - name: tasksOnTaskDispatchedTests
      trigger: onTaskDispatched
      timeout: 540
      collection: tasksOnTaskDispatchedTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"