suite:
  name: v2_testlab
  projectId: functions-integration-tests
  region: us-central1
  description: "V2 TestLab trigger tests"
  version: v2
  service: testlab

  functions:
    - name: testLabOnTestMatrixCompletedTests
      trigger: onTestMatrixCompleted
      timeout: 540
      collection: testLabOnTestMatrixCompletedTests

  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"

  devDependencies:
    typescript: "^4.9.5"