# Firebase Functions V1 Integration Test Suites Configuration
# This unified configuration consolidates all v1 test suite definitions
# Common values are defined in the defaults section to reduce duplication

defaults:
  projectId: functions-integration-tests
  region: us-central1
  timeout: 540
  dependencies:
    firebase-admin: "^12.0.0"
    firebase-functions: "{{sdkTarball}}"
  devDependencies:
    typescript: "^4.9.5"

suites:
  # Firestore triggers
  - name: v1_firestore
    description: "V1 Firestore trigger tests"
    version: v1
    service: firestore
    functions:
      - name: firestoreDocumentOnCreateTests
        trigger: onCreate
        document: "tests/{testId}"
      - name: firestoreDocumentOnDeleteTests
        trigger: onDelete
        document: "tests/{testId}"
      - name: firestoreDocumentOnUpdateTests
        trigger: onUpdate
        document: "tests/{testId}"
      - name: firestoreDocumentOnWriteTests
        trigger: onWrite
        document: "tests/{testId}"

  # Realtime Database triggers
  - name: v1_database
    description: "V1 Realtime Database trigger tests"
    version: v1
    service: database
    functions:
      - name: databaseRefOnCreateTests
        trigger: onCreate
        path: "dbTests/{testId}/start"
      - name: databaseRefOnDeleteTests
        trigger: onDelete
        path: "dbTests/{testId}/start"
      - name: databaseRefOnUpdateTests
        trigger: onUpdate
        path: "dbTests/{testId}/start"
      - name: databaseRefOnWriteTests
        trigger: onWrite
        path: "dbTests/{testId}/start"

  # Pub/Sub triggers
  - name: v1_pubsub
    description: "V1 Pub/Sub trigger tests"
    version: v1
    service: pubsub
    functions:
      - name: pubsubOnPublishTests
        trigger: onPublish
        topic: "pubsubTests"
      - name: pubsubScheduleTests
        trigger: onRun
        schedule: "every 10 hours"

  # Storage triggers
  - name: v1_storage
    description: "V1 Storage trigger tests"
    version: v1
    service: storage
    functions:
      - name: storageOnFinalizeTests
        trigger: onFinalize
      # Note: onDelete is commented out due to bug b/372315689
      # - name: storageOnDeleteTests
      #   trigger: onDelete
      - name: storageOnMetadataUpdateTests
        trigger: onMetadataUpdate

  # Auth triggers (all non-blocking functions)
  - name: v1_auth
    description: "V1 Auth trigger tests"
    version: v1
    service: auth
    functions:
      - name: authUserOnCreateTests
        trigger: onCreate
      - name: authUserOnDeleteTests
        trigger: onDelete
      - name: authUserBeforeCreateTests
        trigger: beforeCreate
        collection: authBeforeCreateTests
      - name: authUserBeforeSignInTests
        trigger: beforeSignIn
        collection: authBeforeSignInTests

  # Auth non-blocking only (for parallel execution)
  - name: v1_auth_nonblocking
    description: "V1 non-blocking Auth trigger tests"
    version: v1
    service: auth
    functions:
      - name: authUserOnCreateTests
        trigger: onCreate
      - name: authUserOnDeleteTests
        trigger: onDelete

  # Auth beforeCreate blocking function (must run separately)
  - name: v1_auth_before_create
    description: "V1 Auth beforeCreate blocking trigger test"
    version: v1
    service: auth
    functions:
      - name: authUserBeforeCreateTests
        trigger: beforeCreate
        collection: authBeforeCreateTests
        blocking: true

  # Auth beforeSignIn blocking function (must run separately)
  - name: v1_auth_before_signin
    description: "V1 Auth beforeSignIn blocking trigger test"
    version: v1
    service: auth
    functions:
      - name: authUserBeforeSignInTests
        trigger: beforeSignIn
        collection: authBeforeSignInTests
        blocking: true

  # Cloud Tasks triggers
  - name: v1_tasks
    description: "V1 Cloud Tasks trigger tests"
    version: v1
    service: tasks
    functions:
      - name: tasksOnDispatchTests
        trigger: onDispatch

  # Remote Config triggers
  - name: v1_remoteconfig
    description: "V1 Remote Config trigger tests"
    version: v1
    service: remoteconfig
    functions:
      - name: remoteConfigOnUpdateTests
        trigger: onUpdate

  # Test Lab triggers
  - name: v1_testlab
    description: "V1 TestLab trigger tests"
    version: v1
    service: testlab
    functions:
      - name: testLabOnCompleteTests
        trigger: onComplete